---
apiVersion: v1
kind: Pod
metadata:
  name: debian-debug
  labels:
    app: debian
spec:
  containers:
  - image: debian:bookworm
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: debian
  restartPolicy: Always