apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: usb
          hostPath:
            path: /dev/ttyUSB0
            #type: CharDevice
        - name: ha-storage
          persistentVolumeClaim:
            claimName: ha-storage
        - name: ha-mysql
          persistentVolumeClaim:
            claimName: ha-mysql
        - name: dbus
          hostPath:
            path: /run/dbus
      containers:
        - image: ghcr.io/home-assistant/home-assistant:2023.10.5 # {"$imagepolicy": "flux-system:homeassistant"}
          name: home-assistant
          volumeMounts:
            - name: ha-storage
              mountPath: /config
            - name: dbus
              mountPath: /run/dbus
            - name: usb
              mountPath: /dev/ttyUSB0
          securityContext:
            privilege: true
          env:
            - name: DISABLE_JEMALLOC
              value: "true"
        - image: mysql:8.1.0 # {"$imagepolicy": "flux-system:homeassistant-mysql"}
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-recorder-pass
                  key: password
          volumeMounts:
            - name: ha-mysql
              mountPath: /var/lib/mysql
