---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-mqsql
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/homeassistant/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-mysql
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-storage
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/homeassistant/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
