---

kind: Kustomization
namespace: homeassistant

commonLabels:
  app.kubernetes.io/name: ha-mcp
  app.kubernetes.io/part-of: homeassistant

resources:
- deployment.yaml
- secrets-sops.yaml
- service.yaml
- ingress.yaml
- automation.yaml
