apiVersion: v1
kind: Secret
metadata:
    name: ha-mcp-secrets
    namespace: homeassistant
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:JxY0Y/MiVNyQtrdes5F+eTGFn/KOhR6uNFb0qmS3T775586ad/4HI3EBBm5LIl8pthT4lXHhFgV2M1SdlspLqa+unmvi8pupVYl31fPZ2Ci29Iiuwj0nA5USJiMETpfuVJn+LGpexfy5mjGhI114PoT8JVrK3p28epNJJAI8SQm/xTT82mXV6BDQRITU1KTMqRgCq2qSyyS4js+4F3UPQZPwmdg5x1ptlFZ9gJlHnFadBpqUKqKU,iv:x9JGFKz4sDgA+1Iq62IsaIX4u+/vmYriLOUExZN34rE=,tag:nghmFmcwd1vakVE/wZsETg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T08:52:30Z"
    mac: ENC[AES256_GCM,data:zBfYOEaSQgyX8QR6O5LsoSAz3UM78+hZoiWPImiIuS1cVnpR8eyiFGJYdrX0IrUB7nBkHxHqV2Rr6oR51Vmkj5ZNyhaGKV+k5VHeTgRpmTRVTXYElhx4ayfallxEEcxHugrJzUD0EQycNrAXdYlTf15ZZf2leXB+M8zLa6IZRvE=,iv:h3wwz9Zbd5M39Esa5lCMX8HjRh9YLT7wYrZ7LvV8a0U=,tag:A+CZwvDdOTgU9JlL5tDRBA==,type:str]
    pgp:
        - created_at: "2026-07-24T08:52:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz3gFPrah4NqAQ/9HU7Ve05vqV3qh1hbIW2/W1mFBiqXdGMMwhhghQUAHNrY
            0BIw6X3JbVXxzqrlvL9ioTBeclYZldmhlowhQmCsRqXBHQMknOkOWKjn1vsVcQGS
            +tRsQm5ni5Eu/oqqYa9jZUc1OvHgovYrP7AtF/X2IJM2ahPqxcWi2Mv1w4AikvM3
            TjawG1mzp4sNl/yOonb6/HnhDJ5lp8KPmE3NrIy6AC+sztFFrGsMqvW8mXGjzqV2
            73WnBcQKsoIEhN4lKP6rctbVop5gR6vlaiUhgckIglLBv2RVhv3dbwEuh39evpJe
            xI68DamJ8xbQpOIDOjPoQPjJjoDb3BBybkSPFuMmseChOnCXJmPVP7kyOMajXqAo
            wiFH+Zh+y5k8TNyYlscAUUQrQ3UK8L/5yTSsVdY1QeFOINW/2MQOqqVbRbWDfrGm
            Ipg2C/urn3hQezT3nQ3mlcyZRiqz/qAmywiu0ZC70rGMsBHxWPcBxcg6raZUKAkz
            ZpPlWtE+g1PKi3Z5zxZPGmHWzBTVPcpeAp1CQ63k5qpFGibNmqDEJCjEM+/vzxGR
            Gny96aYryGsnqHPc/UIOsVI518mcz6CLpA5/P56Hw2QzNJAk53vA80qQ0uJwi8JO
            eb+6+jKMj/AP6t1ATlaCXMwRQsQe/W1Xk+9JKpg00YahqzO8Hhlg3lUmb8XxdkPS
            XAGe5NJCmhbv8/dOrAnUn6G7vS0mvAScyDqarqwPXEIP62QKhM30ANn3Sm1EPYv+
            iNOzmCIj98x+xLeg4P9866ecM4AsxdFMhXIZrV5cCaW0dRD14p1G3gcPXl4I
            =DlTN
            -----END PGP MESSAGE-----
          fp: A54D41469BEC6EAD68F0376C08957C67F1EF936E
    version: 3.13.2
