---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: homeassistant
  annotations:
    kubernetes.io/ingress.class: "traefik"

spec:
  rules:
  - host: z2m.fritz.box
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zigbee2mqtt
            port:
              name: http