---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: homeassistant
spec:
  selector:
    app: zigbee2mqtt
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http