apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
  name: mosquitto
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
      #annotations:
      #  container.apparmor.security.beta.kubernetes.io/matter: unconfined
    spec:
      hostNetwork: true
      volumes:
        - name: mosquitto-data
          hostPath:
            path: "/opt/data/homeassistant/mosquitto/data"
            type: Directory
        - name: mosquitto-config
          hostPath:
            path: "/opt/data/homeassistant/mosquitto/config"
            type: Directory
      containers:
        - image: eclipse-mosquitto:2.0.19 # {"$imagepolicy": "homeassistant:eclipse-mosquitto"}
          name: mosquitto
          volumeMounts:
            - name: mosquitto-data
              mountPath: /mosquitto/data
            - name: mosquitto-config
              mountPath: /mosquitto/config
          securityContext:
            privileged: true
          ports:
          - containerPort: 1883
          - containerPort: 9001