---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 1883
    #targetPort: mqtt
  selector:
    app: mosquitto