---
apiVersion: v1
kind: Service
metadata:
  name: matter
  namespace: homeassistant
spec:
  type: NodePort
  selector:
    app: matter
  ports:
    - protocol: TCP
      port: 5580
      targetPort: 5580
      nodePort: 30558
