---
namespace: homeassistant

resources:
  - ../../app

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              type: cloud
    target:
      kind: (StatefulSet|Deployment|Job)
