---
namespace: homeassistant

resources:
  - ../../app

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              type: controller
    target:
      kind: (StatefulSet|Deployment|Job)
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - blu-nuc
    target:
      kind: (PersistentVolume)
