apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matter
  name: matter
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter
  template:
    metadata:
      labels:
        app: matter
      annotations:
        container.apparmor.security.beta.kubernetes.io/matter: unconfined
    spec:
      hostNetwork: true
      volumes:
        - name: matter
          hostPath:
            path: "/opt/data/homeassistant/matter"
            type: Directory
        - name: dbus
          hostPath:
            path: /run/dbus
      containers:
        - image: ghcr.io/home-assistant-libs/python-matter-server:6.5 # {"$imagepolicy": "flux-system:matter"}
          name: matter
          volumeMounts:
            - name: matter
              mountPath: /data
            - name: dbus
              mountPath: /run/dbus
          securityContext:
            privileged: true
          ports:
          - containerPort: 5530
