---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: matter
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/homeassistant/matter"
  claimRef:
    name: matter
    namespace: homeassistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
